stages:
  - test

"Run tests":
  stage: test
  image: python:alpine
  script:
    - python -m pip install requests types-requests flake8 mypy pytest
    - flake8 .
    - mypy .
    - python3 -m pytest tests
