{
 "title": "Uptime robot",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Uptime robot status",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "uptimerobot_accountdetails" }
   ]
  },
  {
   "title": "Monitors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "uptimerobot_status" }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "uptimerobot_response_time", "legendFormat": "{{ name }}" }
   ]
  }
 ]
}