name: Docker Image CI

on:
  release:
    types: [created]

jobs:
  buildx:
    # strategy:
    #   fail-fast: false
    # 1 job at a time since cron depends on latest
    # max-parallel: 1
    # matrix:
    #   tag:
    #     - latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Set Docker Tag
        run: echo ::set-env name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker container
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          curl -fsSL https://raw.githubusercontent.com/pschmitt/ci-setup-docker-buildx/master/setup.sh | bash
          ./build.sh ${{ matrix.tag }} -p
